version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: ecoguard-broker
    ports:
      - "1883:1883" # Standard TCP for testing
      - "8883:8883" # mTLS port for the final architecture
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: unless-stopped
    
  influxdb:
    image: influxdb:2.7
    container_name: ecoguard-influxdb
    ports:
      - "8086:8086"
    env_file:
      - ./secrets/influxdb.env
    volumes:
      - ./influxdb/data:/var/lib/influxdb2
    restart: unless-stopped

    
  telegraf:
    image: telegraf:1.28
    container_name: ecoguard-telegraf
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./certs:/etc/telegraf/certs:ro
    restart: unless-stopped